package com.sjbb.entity;
// Generated Apr 11, 2020 12:53:19 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Boatseller generated by hbm2java
 */
@Entity
@Table(name = "boatseller", catalog = "fyp")
public class Boatseller implements java.io.Serializable {

	private Integer idSeller;
	private String nameSeller;
	private String email;
	private String phoneNo;
	private String password;
	private Set<Inventory> inventories = new HashSet<Inventory>(0);

	public Boatseller() {
	}

	public Boatseller(String nameSeller, String email, String phoneNo, String password) {
		this.nameSeller = nameSeller;
		this.email = email;
		this.phoneNo = phoneNo;
		this.password = password;
	}

	public Boatseller(String nameSeller, String email, String phoneNo, String password, Set<Inventory> inventories) {
		this.nameSeller = nameSeller;
		this.email = email;
		this.phoneNo = phoneNo;
		this.password = password;
		this.inventories = inventories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_seller", unique = true, nullable = false)
	public Integer getIdSeller() {
		return this.idSeller;
	}

	public void setIdSeller(Integer idSeller) {
		this.idSeller = idSeller;
	}

	@Column(name = "name_seller", nullable = false, length = 20)
	public String getNameSeller() {
		return this.nameSeller;
	}

	public void setNameSeller(String nameSeller) {
		this.nameSeller = nameSeller;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_no", nullable = false, length = 15)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "password", nullable = false, length = 8)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "boatseller")
	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

}
