package com.sjbb.entity;
// Generated Apr 11, 2020 12:53:19 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Delivery generated by hbm2java
 */
@Entity
@Table(name = "delivery", catalog = "fyp")
public class Delivery implements java.io.Serializable {

	private Integer idDeliver;
	private int idOrder;
	private Date dateDeliver;

	public Delivery() {
	}

	public Delivery(int idOrder, Date dateDeliver) {
		this.idOrder = idOrder;
		this.dateDeliver = dateDeliver;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_deliver", unique = true, nullable = false)
	public Integer getIdDeliver() {
		return this.idDeliver;
	}

	public void setIdDeliver(Integer idDeliver) {
		this.idDeliver = idDeliver;
	}

	@Column(name = "id_order", nullable = false)
	public int getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(int idOrder) {
		this.idOrder = idOrder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_deliver", nullable = false, length = 19)
	public Date getDateDeliver() {
		return this.dateDeliver;
	}

	public void setDateDeliver(Date dateDeliver) {
		this.dateDeliver = dateDeliver;
	}

}
