package com.sjbb.entity;
// Generated Apr 11, 2020 12:53:19 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name = "inventory", catalog = "fyp")
public class Inventory implements java.io.Serializable {

	private Integer idIventory;
	private Boatseller boatseller;
	private Category category;
	private String material;
	private String dimension;
	private String waterLevel;
	private int noEngine;
	private String modelEngine;
	private String fuel;
	private float price;
	private int unit;
	private String description;
	private byte[] image;
	private Date publishDate;
	private Date updateDate;

	public Inventory() {
	}

	public Inventory(Boatseller boatseller, Category category, String material, String dimension, String waterLevel,
			int noEngine, String modelEngine, String fuel, float price, int unit, String description, byte[] image,
			Date publishDate, Date updateDate) {
		this.boatseller = boatseller;
		this.category = category;
		this.material = material;
		this.dimension = dimension;
		this.waterLevel = waterLevel;
		this.noEngine = noEngine;
		this.modelEngine = modelEngine;
		this.fuel = fuel;
		this.price = price;
		this.unit = unit;
		this.description = description;
		this.image = image;
		this.publishDate = publishDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_iventory", unique = true, nullable = false)
	public Integer getIdIventory() {
		return this.idIventory;
	}

	public void setIdIventory(Integer idIventory) {
		this.idIventory = idIventory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_seller", nullable = false)
	public Boatseller getBoatseller() {
		return this.boatseller;
	}

	public void setBoatseller(Boatseller boatseller) {
		this.boatseller = boatseller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_category", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "material", nullable = false, length = 50)
	public String getMaterial() {
		return this.material;
	}

	public void setMaterial(String material) {
		this.material = material;
	}

	@Column(name = "dimension", nullable = false, length = 30)
	public String getDimension() {
		return this.dimension;
	}

	public void setDimension(String dimension) {
		this.dimension = dimension;
	}

	@Column(name = "water_level", nullable = false, length = 30)
	public String getWaterLevel() {
		return this.waterLevel;
	}

	public void setWaterLevel(String waterLevel) {
		this.waterLevel = waterLevel;
	}

	@Column(name = "no_engine", nullable = false)
	public int getNoEngine() {
		return this.noEngine;
	}

	public void setNoEngine(int noEngine) {
		this.noEngine = noEngine;
	}

	@Column(name = "model_engine", nullable = false, length = 50)
	public String getModelEngine() {
		return this.modelEngine;
	}

	public void setModelEngine(String modelEngine) {
		this.modelEngine = modelEngine;
	}

	@Column(name = "fuel", nullable = false, length = 20)
	public String getFuel() {
		return this.fuel;
	}

	public void setFuel(String fuel) {
		this.fuel = fuel;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "unit", nullable = false)
	public int getUnit() {
		return this.unit;
	}

	public void setUnit(int unit) {
		this.unit = unit;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "image", nullable = false)
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "publish_date", nullable = false, length = 10)
	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "update_date", nullable = false, length = 10)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
