package com.sjbb.entity;
// Generated Apr 11, 2020 12:53:19 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "fyp")
public class Order implements java.io.Serializable {

	private Integer idOrder;
	private Users users;
	private Date dateOrder;
	private String shipAddress;
	private String recipName;
	private String recipPhone;
	private String methodPayment;
	private float totalOrder;
	private String statusOrder;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public Order() {
	}

	public Order(Users users, Date dateOrder, String shipAddress, String recipName, String recipPhone,
			String methodPayment, float totalOrder, String statusOrder) {
		this.users = users;
		this.dateOrder = dateOrder;
		this.shipAddress = shipAddress;
		this.recipName = recipName;
		this.recipPhone = recipPhone;
		this.methodPayment = methodPayment;
		this.totalOrder = totalOrder;
		this.statusOrder = statusOrder;
	}

	public Order(Users users, Date dateOrder, String shipAddress, String recipName, String recipPhone,
			String methodPayment, float totalOrder, String statusOrder, Set<OrderDetail> orderDetails) {
		this.users = users;
		this.dateOrder = dateOrder;
		this.shipAddress = shipAddress;
		this.recipName = recipName;
		this.recipPhone = recipPhone;
		this.methodPayment = methodPayment;
		this.totalOrder = totalOrder;
		this.statusOrder = statusOrder;
		this.orderDetails = orderDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_order", unique = true, nullable = false)
	public Integer getIdOrder() {
		return this.idOrder;
	}

	public void setIdOrder(Integer idOrder) {
		this.idOrder = idOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cust", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_order", nullable = false, length = 19)
	public Date getDateOrder() {
		return this.dateOrder;
	}

	public void setDateOrder(Date dateOrder) {
		this.dateOrder = dateOrder;
	}

	@Column(name = "ship_address", nullable = false, length = 300)
	public String getShipAddress() {
		return this.shipAddress;
	}

	public void setShipAddress(String shipAddress) {
		this.shipAddress = shipAddress;
	}

	@Column(name = "recip_name", nullable = false, length = 20)
	public String getRecipName() {
		return this.recipName;
	}

	public void setRecipName(String recipName) {
		this.recipName = recipName;
	}

	@Column(name = "recip_phone", nullable = false, length = 15)
	public String getRecipPhone() {
		return this.recipPhone;
	}

	public void setRecipPhone(String recipPhone) {
		this.recipPhone = recipPhone;
	}

	@Column(name = "method_payment", nullable = false, length = 10)
	public String getMethodPayment() {
		return this.methodPayment;
	}

	public void setMethodPayment(String methodPayment) {
		this.methodPayment = methodPayment;
	}

	@Column(name = "total_order", nullable = false, precision = 12, scale = 0)
	public float getTotalOrder() {
		return this.totalOrder;
	}

	public void setTotalOrder(float totalOrder) {
		this.totalOrder = totalOrder;
	}

	@Column(name = "status_order", nullable = false, length = 10)
	public String getStatusOrder() {
		return this.statusOrder;
	}

	public void setStatusOrder(String statusOrder) {
		this.statusOrder = statusOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
